#!/bin/bash

# Verify we are running from master branch
if [ `git rev-parse --abbrev-ref HEAD` != "master" ]; then
    (>&2 echo "Error: Not on branch 'master'")
    exit 1
fi

if [ ! -z `git status -s` ]; then
    (>&2 echo "Error: Workspace contains changes")
    exit 1
fi


#build
JEKYLL_ENV=production bundle exec jekyll b

#check out gh-pages branch
git checkout gh-pages

#Remove all but _site/ folder
mv _site /tmp/
rm -rf *
mv /tmp/_site .

#move all content from _site out
mv _site/* .
rm -rf _site

#commit changes  TODO: use arg to set a commit message
git add -A
git commit -m "latest changes to be published"

#push to branch. Use force, no matter if there are missing updates, we just want to push latest to this branch
git push -f origin gh-pages

#return to master branch
git checkout master

# update algolia index
# ALGOLIA_API_KEY='' bundle exec jekyll algolia

git fetch
git pull

echo 'All done. check latest changes at https://pfd.github.io/mystery-house'
